const bookshelf = [
    {
        title: 'Convenience Store Woman',
        author: 'Sayaka Murata',
        genre: 'Slice of Life Fiction',
        pages: '160',
        date: '02/07/21',
        image: 'convenience',
        rating: '-',
    },    {
        title: 'City of Thieves',
        author: 'David Benioff',
        genre: 'Historical Fiction',
        pages: '258',
        date: '03/14/21',
        image: 'city',
        rating: '-',
    },     {
       title: 'Howl\'s Moving Castle',
       author: 'Diana Wynne Jones',
       genre: 'Fantasy',
       pages: '212',
       date: '04/18/21',
       image: 'howls',
       rating: '-',
    },      {
        title: 'The Handmaid\'s Tale',
        author: 'Margaret Atwood',
        genre: 'Dystopian',
        pages: '311',
        date: '05/30/21',
        image: 'handmaids',
        rating: '-',
    },      {
        title: 'Klara and the Sun',
        author: 'Kazuo Ishiguro',
        genre: 'Science Fiction',
        pages: '320',
        date: '06/26/21',
        image: 'klara',
        rating: '-',
    },      {
        title: 'The Hobbit',
        author: 'J.R.R. Tolkien',
        genre: 'Fantasy',
        pages: '304',
        date: '08/08/21',
        image: 'hobbit',
        rating: '-',
    },      {
        title: 'And Then There Were None',
        author: 'Agatha Christie',
        genre: 'Mystery',
        pages: '272',
        date: '09/12/21',
        image: 'none',
        rating: '4.31/5',
    },      {
        title: 'Interior Chinatown',
        author: 'Charles Yu',
        genre: 'Literary Fiction',
        pages: '288',
        date: '10/10/21',
        image: 'interior',
        rating: '3.83',
    },      {
        title: 'Fever Dream',
        author: 'Samanta Schweblin',
        genre: 'Magical Realism',
        pages: '183',
        date: '11/21/21',
        image: 'fever',
        rating: '4.33',
    },      {
        title: 'First Person Singular',
        author: 'Haruki Murakami',
        genre: 'Short Stories',
        pages: '240',
        date: '12/19/21',
        image: 'first',
        rating: '4.00',
    },      {
        title: 'Beach Read',
        author: 'Emily Henry',
        genre: 'Romance',
        pages: '352',
        date: '01/23/22',
        image: 'beach',
        rating: '3.88',
    },      {
        title: 'No Longer Human',
        author: 'Osamu Dazai',
        genre: 'Literary Fiction',
        pages: '271',
        date: '02/27/22',
        image: 'longer',
        rating: '3.80',
    },      {
        title: 'Foundation',
        author: 'Isaac Asimov',
        genre: 'Science Fiction',
        pages: '244',
        date: '04/03/22',
        image: 'foundation',
        rating: '4.20',
    },      {
        title: 'Drive Your Plow Over the Bones of the Dead',
        author: 'Olga Tokarczuk',
        genre: 'Mystery',
        pages: '274',
        date: '05/22/22',
        image: 'plow',
        rating: '4.25',
    },
];

export default bookshelf;